# Generated by Django 6.0.5 on 2026-05-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('math', models.IntegerField()),
                ('eng', models.CharField()),
                ('kis', models.CharField()),
                ('science', models.CharField()),
                ('pretech', models.CharField()),
                ('agriculture', models.CharField()),
                ('cre', models.CharField()),
                ('carts', models.CharField()),
                ('sst', models.CharField()),
                ('scienceproj', models.IntegerField()),
                ('creativeproj', models.IntegerField()),
                ('agrproj', models.IntegerField()),
                ('prefect', models.IntegerField()),
                ('musicdrama', models.IntegerField()),
                ('sports', models.IntegerField()),
                ('school', models.IntegerField()),
                ('pathway', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
